use_frameworks!

platform :ios, '9.0'

target 'HCRecycleScrollView_Example' do
  pod 'HCRecycleScrollView', :path => '../'

  target 'HCRecycleScrollView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
